                                          ###############################
                                          ### Plagus' Hyprland Config ###
                                          ###############################



source = bind.conf                 #Contains Keybindinf
source = animation.conf            #Contains Hyprland Animations
source = looknfeel.conf            #Contains Aestetics of Window Manager
source = permissions.conf          #Contains Optional Permissions Module
source = startup.conf              #Contains Apps That Startup at boot
source = env.conf                  #Contains The Enviroment Variables
source = input.conf                #Contains The Input Devices
source = colors.conf


################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/

monitor=HDMI-A-2, 1920x1080@60, 0x0, 1
workspace=1,monitor:HDMI-A-2
workspace=2,monitor:HDMI-A-2
workspace=3,monitor:HDMI-A-2
workspace=4,monitor:HDMI-A-2
workspace=5,monitor:HDMI-A-2
workspace=6,monitor:HDMI-A-2


##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$
# windowrule = suppressevent maximize, class:.*
# windowrule = nofocus, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0
# windowrule = nofocus, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0

###############
### PLUGINS ###
###############


#plugin {
#  hyprscrolling {
#      fullscreen_on_one_column = true 
#  }
#  hyprexpo {
#      columns = 2
#      gap_size = 5
#      bg_col = rgb(111111)
#      workspace_method = center 1# [center/first] [workspace] e.g. first 1 or center m+1
#      skip_empty = true
#      gesture_distance = 3 # how far is the "max" for the gesture
#  }
#}

